import logging
from typing import Callable
import scipy as sp

from metaheuristic_designer.utils import MatrixLike
from .probability_distributions import (
    ScipyMultivarDistribution,
    ScipyUnivarDistribution,
    bernoulli_heuristic,
    binomial_heuristic,
    cauchy_heuristic,
    expon_heuristic,
    gamma_heuristic,
    laplace_heuristic,
    multivariate_categorical,
    multivariate_normal_heuristic,
    normal_heuristic,
    poisson_heuristic,
    tikhinov_fisher_heuristic,
    tikhinov_heuristic,
    uniform_heuristic,
    uniform_param_fix,
)

logger = logging.getLogger(__name__)

# fmt: off
scipy_univar_map = {
    # Normal
    "norm": (sp.stats.norm, None, normal_heuristic),
    "normal": (sp.stats.norm, None, normal_heuristic),
    "gauss": (sp.stats.norm, None, normal_heuristic),
    "gaussian": (sp.stats.norm, None, normal_heuristic),

    # Uniform
    "uniform": (sp.stats.uniform, uniform_param_fix, uniform_heuristic),

    # Cauchy
    "cauchy": (sp.stats.cauchy, None, cauchy_heuristic),

    # Laplace
    "laplace": (sp.stats.laplace, None, laplace_heuristic),

    # Gamma
    "gamma": (sp.stats.gamma, None, gamma_heuristic),

    # Exponential
    "exponential": (sp.stats.expon, None, expon_heuristic),
    "expon": (sp.stats.expon, None, expon_heuristic),
    "exp": (sp.stats.expon, None, expon_heuristic),

    # Levy-stable
    "levy_stable": (sp.stats.levy_stable, None, cauchy_heuristic),
    "levy": (sp.stats.levy_stable, None, cauchy_heuristic),

    # Poisson
    "poisson": (sp.stats.poisson, None, poisson_heuristic),
    
    # Bernoulli
    "bernoulli": (sp.stats.bernoulli, None, bernoulli_heuristic),

    # Binomial
    "binom": (sp.stats.binom, None, binomial_heuristic),
    "binomial": (sp.stats.binom, None, binomial_heuristic),

    # Categorical
    "categorical": (sp.stats.rv_discrete, None, None),

    # Tikhinov
    "tikhinov": (sp.stats.vonmises_line, None, tikhinov_heuristic),
    "vonmises": (sp.stats.vonmises_line, None, tikhinov_heuristic),
}

scipy_multivar_map = {
    # mutlivariate gaussian
    "multigauss": (sp.stats.multivariate_normal, None, multivariate_normal_heuristic),
    "multivariate_gauss": (sp.stats.multivariate_normal, None, multivariate_normal_heuristic),
    "multinormal": (sp.stats.multivariate_normal, None, multivariate_normal_heuristic),
    "multivariate_normal": (sp.stats.multivariate_normal, None, multivariate_normal_heuristic),
    "mvn": (sp.stats.multivariate_normal, None, multivariate_normal_heuristic),

    # dirichlet
    "dirichlet": (sp.stats.dirichlet, None, None),

    # Von-Mises Fisher
    "vonmises_fisher": (sp.stats.vonmises_fisher, None, tikhinov_fisher_heuristic),
}

custom_distrib_map = {
    "multicategorical": (multivariate_categorical, None, None)
}
# fmt: on

# fmt: off
distribution_registry = {
    "scipy-univar": scipy_univar_map,
    "scipy-multivar": scipy_multivar_map,
    "custom": custom_distrib_map
}
# fmt: on


def create_prob_distribution(distribution_name: str, population_matrix:MatrixLike, parameter_heuristic_fn: Callable = None, **kwargs):
    distrib_name_lower = distribution_name.lower()

    if "." in distrib_name_lower:
        distrib_reg_name, distrib_name_lower, *_ = distrib_name_lower.split(".")
    else:
        distrib_reg_name = None
        for k, v in distribution_registry.items():
            if distrib_name_lower in v:
                if distrib_reg_name is None:
                    distrib_reg_name = k
                else:
                    logger.warning("Found duplicate distribuiton '%s' in both registries '%s' and '%s'", distrib_name_lower, distrib_reg_name, k)

        if distrib_reg_name is None:
            raise ValueError("Distribution not found in any registry")

    distrib_fn, param_processor, param_heuristic = distribution_registry[distrib_reg_name][distrib_name_lower]
    if param_processor is not None:
        kwargs = param_processor(**kwargs)
    if parameter_heuristic_fn is None:
        param_heuristic = parameter_heuristic_fn
    if param_heuristic is None:
        param_heuristic = lambda _, **kwargs: kwargs
    kwargs = param_heuristic(population_matrix, **kwargs)

    if distrib_reg_name == "scipy-univar":
        distrib = ScipyUnivarDistribution(distrib_fn, **kwargs)
    elif distrib_reg_name == "scipy-multivar":
        distrib = ScipyMultivarDistribution(distrib_fn, **kwargs)
    elif distrib_reg_name == "custom":
        distrib = distrib_fn(**kwargs)

    return distrib


# def add_operator_entry(operator_fn: callable, operator_name: str, operator_registry: str = "custom", preserves_order=False):
#     """
#     Adds an operator so it can be generated by a the operator factory.

#     Parameters
#     ----------
#     operator_fn
#         Callable that gets a population and a random_state to perturb the population. It is highly recommended to
#         use one of the available wrappers OperatorVectorDef, OperatorRandomDef, ...
#     operator_name
#         Name to give the operator in the registry.
#     operator_registry, optional
#         Name of the registry to add this operator to. New names simply generate a new registry, by default "custom"
#     """

#     if operator_registry not in all_ops_map:
#         all_ops_map[operator_registry] = {}
#         logger.info('Added a new operator registry named "%s"', operator_registry)

#     op_reg_map = all_ops_map[operator_registry]
#     if operator_name in op_reg_map:
#         logger.warning('Overwritten operator "%s" in registry "%s"', operator_name, operator_registry)
#     op_reg_map[operator_name] = operator_fn

#     if preserves_order:
#         order_preserving_operators.add(operator_name)

#     logger.info('Added a new operator "%s" in registry "%s"', operator_name, operator_registry)


# def list_operators():
#     all_ops_list = []
#     for registry_name, registry_map in all_ops_map.items():
#         for op_name in registry_map.keys():
#             all_ops_list.append(f"{registry_name}.{op_name}")
#     return all_ops_list
